{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe9126e9-11d8-4d48-9c71-e352a1029720",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "   \n",
    "    \n",
    "ans.\n",
    "\n",
    "In Python, when creating a custom exception, it is essential to inherit from the `Exception` class or one of its subclasses.\n",
    "The `Exception` class is the base class for all built-in exceptions in Python.\n",
    "By inheriting from the `Exception` class, your custom exception inherits \n",
    "all the functionalities and behaviors of the base class,making\n",
    "it a valid exception type that can be used in `try`-`except` blocks for error handling.\n",
    "\n",
    "Here are the reasons why we should use the `Exception` class while creating a custom exception:\n",
    "\n",
    "1. **Inheriting Common Functionality:** \n",
    "        The `Exception` class provides common functionality and methods that are required for handling exceptions effectively.\n",
    "    When you inherit from `Exception`, your custom exception gains access to important methods like `__str__` (to provide the error message)\n",
    "    and `__repr__` (to provide a string representation of the exception). This makes your custom exception behave like any other built-in exception, \n",
    "    facilitating consistent error handling across your codebase.\n",
    "\n",
    "2. **Interoperability:**\n",
    "       Inheriting from `Exception` ensures that your custom exception can be used interchangeably with other built-in exceptions in Python.\n",
    "    This allows you to catch your custom exception along with standard exceptions using the same `except` block.\n",
    "\n",
    "3. **Consistency and Conventions:**\n",
    "     Following the convention of inheriting from `Exception` allows other developers who read your code to quickly recognize that\n",
    "    your class is intended to be used as an exception. It makes your code more readable and consistent with\n",
    "    standard Python coding practices.\n",
    "\n",
    "Here's an example to illustrate the creation of a custom exception by inheriting from the `Exception` class:\n",
    "\n",
    "\n",
    "class CustomError(Exception):\n",
    "    \"\"\"Custom exception class inheriting from Exception.\"\"\"\n",
    "\n",
    "    def __init__(self, message):\n",
    "        super().__init__(message)\n",
    "        self.message = message\n",
    "\n",
    "def process_data(data):\n",
    "    if not data:\n",
    "        raise CustomError(\"Invalid data. Data cannot be empty.\")\n",
    "    # Process the data here\n",
    "\n",
    "try:\n",
    "    data = []\n",
    "    process_data(data)\n",
    "except CustomError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "795c58d7-1386-477d-8988-50653ba5314d",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "\n",
    "ans.\n",
    "\n",
    "In Python, exceptions are organized into a hierarchy, where some exceptions are subclasses of others.\n",
    "The built-in Exception class serves as the base class for all exceptions, \n",
    "and other exception classes are derived from it. To print the Python Exception Hierarchy,\n",
    "we can use the issubclass() function to check the inheritance relationships between exception classes.\n",
    "\n",
    "\n",
    "Here's a Python program to print the Python Exception Hierarchy:\n",
    "\n",
    "def print_exception_hierarchy(base_class, indent=0):\n",
    "    for subclass in base_class.__subclasses__():\n",
    "        print(' ' * indent + subclass.__name__)\n",
    "        print_exception_hierarchy(subclass, indent + 2)\n",
    "\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0841cf0-febb-41b4-8686-4d091e2779fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "ans.\n",
    "\n",
    "The ArithmeticError class in Python is a base class for arithmetic-related exceptions.\n",
    "It serves as a superclass for exceptions that are raised during arithmetic operations. \n",
    "Some of the common errors defined in the ArithmeticError class include:\n",
    "\n",
    " ZeroDivisionError:\n",
    "    This exception is raised when attempting to divide a number by zero.\n",
    "\n",
    " OverflowError: \n",
    "        This exception is raised when the result of an arithmetic operation exceeds the maximum representable value for a numeric type.\n",
    "\n",
    "Let's explain these two errors with examples:\n",
    "\n",
    "a. ZeroDivisionError:\n",
    "This exception occurs when you attempt to divide a number by zero, which is not a valid mathematical operation.\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        return result\n",
    "    except ZeroDivisionError:\n",
    "        return \"Error: Division by zero is not allowed.\"\n",
    "\n",
    "# Example 1: Valid division\n",
    "numerator = 10\n",
    "denominator = 2\n",
    "result = divide_numbers(numerator, denominator)\n",
    "print(result)  # Output: 5.0\n",
    "\n",
    "# Example 2: Division by zero\n",
    "denominator = 0\n",
    "result = divide_numbers(numerator, denominator)\n",
    "print(result)  # Output: Error: Division by zero is not allowed.\n",
    "\n",
    "\n",
    "b. OverflowError:\n",
    "This exception occurs when the result of\n",
    "an arithmetic operation exceeds the maximum representable value for a numeric type.\n",
    "\n",
    "def calculate_factorial(n):\n",
    "    try:\n",
    "        result = 1\n",
    "        for i in range(1, n + 1):\n",
    "            result *= i\n",
    "        return result\n",
    "    except OverflowError:\n",
    "        return \"Error: Result exceeds the maximum representable value.\"\n",
    "\n",
    "# Example 1: Valid calculation\n",
    "num = 10\n",
    "factorial = calculate_factorial(num)\n",
    "print(factorial)  # Output: 3628800\n",
    "\n",
    "# Example 2: Large calculation causing OverflowError\n",
    "num = 10000\n",
    "factorial = calculate_factorial(num)\n",
    "print(factorial)  # Output: Error: Result exceeds the maximum representable value.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58fdc5b7-2d10-463a-8c26-01b7e3caa004",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "ans.\n",
    "\n",
    "The LookupError class in Python is a base class for exceptions that occur \n",
    "when a lookup or indexing operation fails due to the absence of a key or index in a collection. \n",
    "It serves as a superclass for exceptions like KeyError and IndexError, which are specific cases of lookup failures.\n",
    "\n",
    "The LookupError class is useful for handling situations where you are accessing elements in a collection \n",
    "(e.g., dictionary, list) using keys or indices, and the specified key or index is not found in the collection.\n",
    "\n",
    "Let's explain two specific exceptions derived from LookupError: KeyError and IndexError, along with examples for each:\n",
    "\n",
    "*KeyError:\n",
    "  This exception occurs when you try to access a dictionary element using a key that does not exist in the dictionary.\n",
    "\n",
    "\n",
    "def get_student_name(student_dict, roll_number):\n",
    "    try:\n",
    "        name = student_dict[roll_number]\n",
    "        return name\n",
    "    except KeyError:\n",
    "        return \"Error: Roll number not found in the student dictionary.\"\n",
    "\n",
    "# Example: Dictionary representing student names with roll numbers\n",
    "students = {101: 'Alice', 102: 'Bob', 103: 'Charlie'}\n",
    "\n",
    "# Accessing student names by roll number\n",
    "print(get_student_name(students, 102))  # Output: Bob\n",
    "print(get_student_name(students, 104))  # Output: Error: Roll number not found in the student dictionary.\n",
    "\n",
    "\n",
    "\n",
    "*IndexError:\n",
    "  This exception occurs when you try to access an element from a sequence \n",
    "  (e.g., list, tuple, string) using an index that is out of range.\n",
    "    \n",
    "def get_item_from_list(data_list, index):\n",
    "    try:\n",
    "        item = data_list[index]\n",
    "        return item\n",
    "    except IndexError:\n",
    "        return \"Error: Index out of range.\"\n",
    "\n",
    "# Example: List of numbers\n",
    "numbers = [10, 20, 30, 40, 50]\n",
    "\n",
    "# Accessing elements by index\n",
    "print(get_item_from_list(numbers, 2))  # Output: 30\n",
    "print(get_item_from_list(numbers, 6))  # Output: Error: Index out of range.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20791c92-59e3-457f-a0df-1ad23ce441f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. Explain ImportError. What is Module Not Found Error?\n",
    "\n",
    "ans.\n",
    "\n",
    "ImportError:\n",
    "ImportError is a built-in Python exception that occurs when there is an issue while\n",
    "importing a module or a specific attribute from a module. \n",
    "It typically arises when Python cannot find the module or the attribute you are trying to import, \n",
    "or when there are errors in the module being imported.\n",
    "\n",
    "There are various reasons that can lead to an ImportError:\n",
    "\n",
    "The module or package you are trying to import is not installed in the Python environment.\n",
    "The module file has errors in it, such as syntax errors or runtime errors.\n",
    "The module is in a different directory, and Python cannot find it in the search paths.\n",
    "There might be circular dependencies between modules that cause an issue during import.\n",
    "\n",
    "ModuleNotFoundError:\n",
    "  ModuleNotFoundError is a specific type of ImportError that occurs when Python cannot find the module you are trying to import.\n",
    "It was introduced in Python 3.6 as a more informative and specific exception for module import failures.\n",
    "\n",
    "Prior to Python 3.6, attempting to import a non-existent module would raise a generic ImportError. \n",
    "With the introduction of ModuleNotFoundError, it is now easier to distinguish between \n",
    "a module not found error and other types of import errors.\n",
    "\n",
    "Here's an example to illustrate ImportError and ModuleNotFoundError:\n",
    "\n",
    "Consider a scenario where you have a Python script named main.py\n",
    "that tries to import a module named missing_module that does not exist.\n",
    "\n",
    "main.py:\n",
    "    \n",
    "    \n",
    "try:\n",
    "    import missing_module\n",
    "except ImportError as e:\n",
    "    print(f\"ImportError: {e}\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7948945f-6775-4584-8669-34f9f9973265",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "ans.\n",
    "\n",
    "Exception handling is an essential aspect of writing robust and maintainable Python code. \n",
    "Following best practices for exception handling can make your code more reliable, \n",
    "easier to debug, and enhance the overall user experience. \n",
    "Here are some best practices for exception handling in Python:\n",
    "\n",
    "1. **Specific Exception Handling:**\n",
    "    Catch specific exceptions rather than using a broad `except` block.\n",
    "    This allows you to handle different types of exceptions differently and \n",
    "    provides more informative error messages. Avoid using a generic `except`\n",
    "    block as it can hide unexpected errors and make debugging difficult.\n",
    "\n",
    "2. **Keep the `try` Block Minimal:**\n",
    "    Only put the code that might raise an exception inside the `try` block. \n",
    "    Keeping the `try` block minimal makes it easier to identify the potential \n",
    "    sources of exceptions and improves code readability.\n",
    "\n",
    "3. **Use `finally` for Cleanup:** \n",
    "    Use the `finally` block for cleanup code that needs to be executed regardless of\n",
    "    whether an exception occurred or not. Common use cases include closing files, \n",
    "    releasing resources, or finalizing database connections.\n",
    "\n",
    "4. **Avoid Using Bare `except`:**\n",
    "    Avoid using `except:` without specifying the exception type. Bare `except` can catch\n",
    "    unexpected exceptions, making it harder to diagnose issues.\n",
    "    Instead, use specific exception types or the base `Exception` class if necessary.\n",
    "\n",
    "5. **Log Exceptions:**\n",
    "    When handling exceptions, log the details of the exception, including the error message,\n",
    "    traceback, and relevant context information. Logging exceptions helps in debugging and\n",
    "    understanding what went wrong during the program's execution.\n",
    "\n",
    "6. **Raising Custom Exceptions:** \n",
    "   Raise custom exceptions when appropriate. Custom exceptions allow you to provide meaningful\n",
    "    error messages that are specific to your application.\n",
    "    This makes it easier for users and developers to understand the cause of errors.\n",
    "\n",
    "7. **Graceful Error Messages:** \n",
    "   Provide user-friendly and informative error messages for exceptions.\n",
    "    Avoid displaying raw traceback messages to end-users, as it may confuse them.\n",
    "    Instead, present error messages in a way that assists users in understanding what \n",
    "    went wrong and how to resolve the issue.\n",
    "\n",
    "8. **Avoid Using Exceptions for Flow Control:**\n",
    "    Exceptions should be used for exceptional cases, not for regular flow control. \n",
    "    Using exceptions as a way to handle expected cases can negatively impact the performance \n",
    "    and maintainability of your code.\n",
    "\n",
    "9. **Context Managers (with statement):**\n",
    "   Use context managers (the `with` statement) for handling resources that need to be cleaned up automatically,\n",
    "    such as file handling, database connections, or network sockets.\n",
    "    Context managers help ensure that resources are properly released, even if an exception occurs.\n",
    "\n",
    "10. **Unit Tests for Exception Handling:** \n",
    "   Write unit tests to cover exception scenarios in your code. Ensure that exceptions are raised and \n",
    "    handled correctly in different situations. Unit tests help verify that your exception handling logic works as expected.\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
